### ISSUE TITLE
请问如何得到 mupdf 的dll 文件

### ISSUE THREAD

**Issue by sailist** [dicarne/PaperPDF#1]
您好，我想请教一下 `libmupdf.dll`  是如何编译出来的，还是是从 SumtraPDF 安装文件下下载的，如果是的话，版本是多少呢？

以及想问一下 dll 函数的参数您是怎么确定的呢，这方面我还没怎么接触过...

**Comment by dicarne** [comment]
是用源码自己编译的。
首先在官网[Mupdf](https://mupdf.com/)下载源码，打开platform/win32/mupdf.sln，可以在VS中看到很多项目。其中libmupdf是核心代码，我们需要把这个库编译出来。
VS中C++导出库函数，需要指定导出哪些函数，直接编译库文件的话，其他程序是无法调用的。
在libmupdf中创建一个export.def文件，指定需要导出的函数，我的导出文件如下：
```
LIBRARY libmupdf

EXPORTS

fz_new_context_imp

fz_free_context=fz_drop_context

fz_open_file_w

fz_register_document_handlers

fz_open_document_with_stream

fz_count_pages

fz_load_page

fz_free_page=fz_drop_page

fz_close=fz_drop_stream

fz_free_device=fz_drop_device

fz_bound_page

fz_close_document=fz_drop_document

fz_page_separations

fz_clear_pixmap_with_value

fz_new_draw_device

fz_run_page

fz_pixmap_samples

fz_drop_pixmap

fz_device_rgb

fz_new_pixmap

fz_new_pixmap_from_page

fz_close_device

fz_open_document

fz_scale

fz_pre_rotate

fz_new_pixmap_from_page_number

fz_pixmap_width

fz_pixmap_height
```

具体如何编写可以你查一查，主要是要找出究竟需要导出哪些函数。
我是找官方教程，用C编写一个PDF阅读器，把教程中提到的所有函数都加进这个清单中，然后利用VS编译这个工程。在输出目录下即可找到libmupdf.dll。

最后，把这个dll拷贝到C#工程的输出目录下，和输出的exe同一个目录，这样应用程序才能找到动态链接库，才能调用库函数。

在C#中调用C库函数，需要声明一个和库函数相同签名的C#静态函数：
```
        [DllImport(DLL, EntryPoint = "fz_close_document")]
        public static extern IntPtr CloseDocument(IntPtr ctx, IntPtr doc);
```
利用DllImport这个Attr，EntryPoint 填写对应C函数名称，函数签名要和C函数一致（参数抄c函数的定义，不知道具体定义？源码都在，拿着函数名搜索就可以了。C#中的函数名不需要完全一样，但参数的类型、顺序要一样。）。

需要注意的是，C中的指针，在C#中为IntPtr，C中库函数要用的某些struct，在C#中定义一个相同结构的struct即可。（记住字段的顺序要一样）因为C和C#的struct并没有什么差别，可以直接互调用。

通常将库函数封装成可以方便调用的C#类，使用会比较方便，参见： https://github.com/dicarne/PaperPDF/blob/master/PaperPDF/MuPdf.cs

**Comment by sailist** [comment]
明白了！非常感谢！
